Class {
	#name : 'MicHeaderCapitalizationRule',
	#superclass : 'MicRule',
	#instVars : [
		'shouldVerifyHeadersAreNotCapitalized'
	],
	#category : 'Microdown-Rules-Capitalization',
	#package : 'Microdown-Rules',
	#tag : 'Capitalization'
}

{ #category : 'asserting' }
MicHeaderCapitalizationRule >> shouldVerifyHeadersAreNotCapitalized [
	
	shouldVerifyHeadersAreNotCapitalized := true
]

{ #category : 'asserting' }
MicHeaderCapitalizationRule >> shouldVerifyHeadersAreNotCapitilized [
	
	shouldVerifyHeadersAreNotCapitalized := true
]
