Class {
	#name : 'MicRuleHeaderCheckerStrategy',
	#superclass : 'Object',
	#instVars : [
		'checker'
	],
	#category : 'Microdown-Rules-CapitalizationUnderway',
	#package : 'Microdown-Rules',
	#tag : 'CapitalizationUnderway'
}

{ #category : 'accessing' }
MicRuleHeaderCheckerStrategy >> checker [

	^ checker
]

{ #category : 'accessing' }
MicRuleHeaderCheckerStrategy >> checker: anObject [

	checker := anObject
]
