Class {
	#name : 'MicUseofWrongVocabulary',
	#superclass : 'Object',
	#instVars : [
		'text',
		'pattern'
	],
	#category : 'Microdown-Rules',
	#package : 'Microdown-Rules'
}

{ #category : 'accessing' }
MicUseofWrongVocabulary >> pattern [

	^ pattern
]

{ #category : 'accessing' }
MicUseofWrongVocabulary >> pattern: anObject [

	pattern := anObject
]

{ #category : 'accessing' }
MicUseofWrongVocabulary >> text [

	^ text
]

{ #category : 'accessing' }
MicUseofWrongVocabulary >> text: anObject [

	text := anObject
]
